apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      containers:
        - name: hello
          image: marselester/prom-on-k8s:v3
          ports:
            - containerPort: 8000
